// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package deviceshandler

import (
	"context"

	"github.com/PritOriginal/nethub-back/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDevicesService creates a new instance of MockDevicesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDevicesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDevicesService {
	mock := &MockDevicesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDevicesService is an autogenerated mock type for the DevicesService type
type MockDevicesService struct {
	mock.Mock
}

type MockDevicesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDevicesService) EXPECT() *MockDevicesService_Expecter {
	return &MockDevicesService_Expecter{mock: &_m.Mock}
}

// AddDevice provides a mock function for the type MockDevicesService
func (_mock *MockDevicesService) AddDevice(ctx context.Context, device models.Device) (models.Device, error) {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for AddDevice")
	}

	var r0 models.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Device) (models.Device, error)); ok {
		return returnFunc(ctx, device)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Device) models.Device); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Get(0).(models.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Device) error); ok {
		r1 = returnFunc(ctx, device)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDevicesService_AddDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDevice'
type MockDevicesService_AddDevice_Call struct {
	*mock.Call
}

// AddDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - device models.Device
func (_e *MockDevicesService_Expecter) AddDevice(ctx interface{}, device interface{}) *MockDevicesService_AddDevice_Call {
	return &MockDevicesService_AddDevice_Call{Call: _e.mock.On("AddDevice", ctx, device)}
}

func (_c *MockDevicesService_AddDevice_Call) Run(run func(ctx context.Context, device models.Device)) *MockDevicesService_AddDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Device
		if args[1] != nil {
			arg1 = args[1].(models.Device)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDevicesService_AddDevice_Call) Return(device1 models.Device, err error) *MockDevicesService_AddDevice_Call {
	_c.Call.Return(device1, err)
	return _c
}

func (_c *MockDevicesService_AddDevice_Call) RunAndReturn(run func(ctx context.Context, device models.Device) (models.Device, error)) *MockDevicesService_AddDevice_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDevice provides a mock function for the type MockDevicesService
func (_mock *MockDevicesService) DeleteDevice(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDevicesService_DeleteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDevice'
type MockDevicesService_DeleteDevice_Call struct {
	*mock.Call
}

// DeleteDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockDevicesService_Expecter) DeleteDevice(ctx interface{}, id interface{}) *MockDevicesService_DeleteDevice_Call {
	return &MockDevicesService_DeleteDevice_Call{Call: _e.mock.On("DeleteDevice", ctx, id)}
}

func (_c *MockDevicesService_DeleteDevice_Call) Run(run func(ctx context.Context, id int)) *MockDevicesService_DeleteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDevicesService_DeleteDevice_Call) Return(err error) *MockDevicesService_DeleteDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDevicesService_DeleteDevice_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockDevicesService_DeleteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeviceById provides a mock function for the type MockDevicesService
func (_mock *MockDevicesService) GetDeviceById(ctx context.Context, id int) (models.Device, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceById")
	}

	var r0 models.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.Device, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.Device); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDevicesService_GetDeviceById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeviceById'
type MockDevicesService_GetDeviceById_Call struct {
	*mock.Call
}

// GetDeviceById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockDevicesService_Expecter) GetDeviceById(ctx interface{}, id interface{}) *MockDevicesService_GetDeviceById_Call {
	return &MockDevicesService_GetDeviceById_Call{Call: _e.mock.On("GetDeviceById", ctx, id)}
}

func (_c *MockDevicesService_GetDeviceById_Call) Run(run func(ctx context.Context, id int)) *MockDevicesService_GetDeviceById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDevicesService_GetDeviceById_Call) Return(device models.Device, err error) *MockDevicesService_GetDeviceById_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDevicesService_GetDeviceById_Call) RunAndReturn(run func(ctx context.Context, id int) (models.Device, error)) *MockDevicesService_GetDeviceById_Call {
	_c.Call.Return(run)
	return _c
}

// GetDevices provides a mock function for the type MockDevicesService
func (_mock *MockDevicesService) GetDevices(ctx context.Context, params models.GetDevicesParams) ([]models.Device, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetDevices")
	}

	var r0 []models.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetDevicesParams) ([]models.Device, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetDevicesParams) []models.Device); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetDevicesParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDevicesService_GetDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDevices'
type MockDevicesService_GetDevices_Call struct {
	*mock.Call
}

// GetDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - params models.GetDevicesParams
func (_e *MockDevicesService_Expecter) GetDevices(ctx interface{}, params interface{}) *MockDevicesService_GetDevices_Call {
	return &MockDevicesService_GetDevices_Call{Call: _e.mock.On("GetDevices", ctx, params)}
}

func (_c *MockDevicesService_GetDevices_Call) Run(run func(ctx context.Context, params models.GetDevicesParams)) *MockDevicesService_GetDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetDevicesParams
		if args[1] != nil {
			arg1 = args[1].(models.GetDevicesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDevicesService_GetDevices_Call) Return(devices []models.Device, err error) *MockDevicesService_GetDevices_Call {
	_c.Call.Return(devices, err)
	return _c
}

func (_c *MockDevicesService_GetDevices_Call) RunAndReturn(run func(ctx context.Context, params models.GetDevicesParams) ([]models.Device, error)) *MockDevicesService_GetDevices_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDevice provides a mock function for the type MockDevicesService
func (_mock *MockDevicesService) UpdateDevice(ctx context.Context, device models.Device) (models.Device, error) {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDevice")
	}

	var r0 models.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Device) (models.Device, error)); ok {
		return returnFunc(ctx, device)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Device) models.Device); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Get(0).(models.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Device) error); ok {
		r1 = returnFunc(ctx, device)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDevicesService_UpdateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDevice'
type MockDevicesService_UpdateDevice_Call struct {
	*mock.Call
}

// UpdateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - device models.Device
func (_e *MockDevicesService_Expecter) UpdateDevice(ctx interface{}, device interface{}) *MockDevicesService_UpdateDevice_Call {
	return &MockDevicesService_UpdateDevice_Call{Call: _e.mock.On("UpdateDevice", ctx, device)}
}

func (_c *MockDevicesService_UpdateDevice_Call) Run(run func(ctx context.Context, device models.Device)) *MockDevicesService_UpdateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Device
		if args[1] != nil {
			arg1 = args[1].(models.Device)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDevicesService_UpdateDevice_Call) Return(device1 models.Device, err error) *MockDevicesService_UpdateDevice_Call {
	_c.Call.Return(device1, err)
	return _c
}

func (_c *MockDevicesService_UpdateDevice_Call) RunAndReturn(run func(ctx context.Context, device models.Device) (models.Device, error)) *MockDevicesService_UpdateDevice_Call {
	_c.Call.Return(run)
	return _c
}
